import Saki_Helper as skh

#Features (use "-" to separate words in the same option)
DFlamis = {'home':{'clipboard':{'copiar':{'copiar','copio'},
                                'pegar':{'pegar','pego'},'cortar':{'corto','cortar'},
                                'copiar-formato':{'copio','copiar','formato'}},
                    'font':{'fuente':{'tipo','letra','fuente','cambiar','cambio','forma'},
                                    'tamaño':{'talla','grande','agrandar','agrando','achicar','achico','hacer','hago','pequeño','pequeña'},
                                    'borrar formato':{'quito','quitar','formato','borro','borrar'},
                                    'negrita':{'gordo','gordita','gruezo','grueza'},
                                    'cursiva':{'inclino','letra','inclinada','chueca'},
                                    'subrayado':{'subrayo','subrrayo','subrayaba','subrrayaba','raya', 'abajo','rayita'}},
                    'paragraph':{}},
            'insert':{},
            'draw':{},
            'design':{},
            'layout':{'configurar-páginas':{'márgenes':{},
                                            'orientacion':{},
                                            'tamaño':{},
                                            'columnas':{'una':{'un','una','columna','1'},
                                                        'dos':{'dos','columna','columnas','2'},
                                                        'tres':{'tres','columna','columnas','3'},
                                                        'más-columnas':{'número-de-columnas':{'columna','columnas','varias','cuatro','cinco','muchas'},
                                                                        'línea-entre-columnas':{'raya','rayita','entre','enmedio','medio','columna','columnas','linea','lineas','liniesita'}}},
                                            'saltos':{}},
                        'párrafo':{},
                        'organizar':{}},
            'references':{},
            'mailings':{},
            'reviews':{}}